version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 8
    commands:
      - npm i npm@latest -g
      - pip install --upgrade awscli
      - yum update -y
      - yum install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test
      - npm run cy:run
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://kettlebell-coders-app --acl public-read