FROM node:10

RUN apt-get update && \
  apt-get install -y \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    xvfb


WORKDIR '/kettlebell-coders'

COPY package*.json ./

RUN npm install

COPY . .

#Setting the default RUN command for our built container to run our test suite.
CMD ["npm", "run", "test"]